<?php

declare(strict_types=1);

/*
 * This file is part of a FuelApp project.
 *
 * (c) Lorenzo Marozzo <lorenzo.marozzo@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260217203857 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Init receipts, receipt_lines and stations tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE receipt_lines (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fuel_type VARCHAR(32) NOT NULL, quantity_milli_liters INT NOT NULL, unit_price_cents_per_liter INT NOT NULL, vat_rate_percent INT NOT NULL, receipt_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AB9938A62B5CA896 ON receipt_lines (receipt_id)');

        $this->addSql('CREATE TABLE receipts (id UUID NOT NULL, issued_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, total_cents INT NOT NULL, station_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1DEBE3A221BDB235 ON receipts (station_id)');

        $this->addSql('CREATE TABLE stations (id UUID NOT NULL, name VARCHAR(255) NOT NULL, street_name VARCHAR(255) NOT NULL, postal_code VARCHAR(20) NOT NULL, city VARCHAR(100) NOT NULL, latitude_micro_degrees INT DEFAULT NULL, longitude_micro_degrees INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX station_identity ON stations (name, street_name, postal_code, city)');

        $this->addSql('ALTER TABLE receipt_lines ADD CONSTRAINT FK_AB9938A62B5CA896 FOREIGN KEY (receipt_id) REFERENCES receipts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE receipts ADD CONSTRAINT FK_1DEBE3A221BDB235 FOREIGN KEY (station_id) REFERENCES stations (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE receipt_lines DROP CONSTRAINT FK_AB9938A62B5CA896');
        $this->addSql('ALTER TABLE receipts DROP CONSTRAINT FK_1DEBE3A221BDB235');

        $this->addSql('DROP TABLE receipt_lines');
        $this->addSql('DROP TABLE receipts');
        $this->addSql('DROP TABLE stations');
    }
}
