<?php

declare(strict_types=1);

/*
 * This file is part of a FuelApp project.
 *
 * (c) Lorenzo Marozzo <lorenzo.marozzo@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260218144118 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Use UUIDs for receipt lines';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE receipt_lines DROP CONSTRAINT receipt_lines_pkey');
        $this->addSql('ALTER TABLE receipt_lines DROP COLUMN id');
        $this->addSql('ALTER TABLE receipt_lines ADD id UUID NOT NULL');
        $this->addSql('ALTER TABLE receipt_lines ADD PRIMARY KEY (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE receipt_lines DROP CONSTRAINT receipt_lines_pkey');
        $this->addSql('ALTER TABLE receipt_lines DROP COLUMN id');
        $this->addSql('ALTER TABLE receipt_lines ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE receipt_lines ADD PRIMARY KEY (id)');
    }
}
